Repository Pradumnasaraf/gencli, pull requests merged in 2024-07, with the labels that each got.

#3 fix: release the root command
  CONTRIBUTING.md
  README.md
  cmd/chatCmd.go
  cmd/rootCmd.go
Labels: enhancement

#5 fix: root command back to "gencli"
  README.md
  cmd/rootCmd.go
Labels: bug

#7 feat: Rename chatCmd to searchCmd and add word count flag
  README.md
  cmd/rootCmd.go
  cmd/searchCmd.go
Labels: documentation, feature

#9 feat: Improve the response format
  cmd/searchCmd.go
Labels: feature
